/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppExamsRouteImport } from './routes/app.exams'
import { Route as AppLearnRouteImport } from './routes/app.learn'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppMyCooksRouteImport } from './routes/app.my-cooks'
import { Route as AppPlanRouteImport } from './routes/app.plan'
import { Route as AppPracticeRouteImport } from './routes/app.practice'
import { Route as AppProgressRouteImport } from './routes/app.progress'
import { Route as AppQuizRouteImport } from './routes/app.quiz'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppLearnIndexRouteImport } from './routes/app.learn.index'
import { Route as AppLearnLessonIdRouteImport } from './routes/app.learn.$lessonId'
import { Route as AppSolveIndexRouteImport } from './routes/app.solve.index'
import { Route as AppSolveIdRouteImport } from './routes/app.solve.$id'
import { Route as AppSolveWorksheetRouteImport } from './routes/app.solve.worksheet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsRoute = AppExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnRoute = AppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppMyCooksRoute = AppMyCooksRouteImport.update({
  id: '/my-cooks',
  path: '/my-cooks',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeRoute = AppPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizRoute = AppQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnIndexRoute = AppLearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLearnRoute,
} as any)
const AppLearnLessonIdRoute = AppLearnLessonIdRouteImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => AppLearnRoute,
} as any)
const AppSolveIndexRoute = AppSolveIndexRouteImport.update({
  id: '/solve/',
  path: '/solve/',
  getParentRoute: () => AppRoute,
} as any)
const AppSolveIdRoute = AppSolveIdRouteImport.update({
  id: '/solve/$id',
  path: '/solve/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSolveWorksheetRoute = AppSolveWorksheetRouteImport.update({
  id: '/solve/worksheet',
  path: '/solve/worksheet',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/exams': typeof AppExamsRoute
  '/app/learn': typeof AppLearnRouteWithChildren
  '/app/library': typeof AppLibraryRoute
  '/app/my-cooks': typeof AppMyCooksRoute
  '/app/plan': typeof AppPlanRoute
  '/app/practice': typeof AppPracticeRoute
  '/app/progress': typeof AppProgressRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/learn/$lessonId': typeof AppLearnLessonIdRoute
  '/app/solve/$id': typeof AppSolveIdRoute
  '/app/solve/worksheet': typeof AppSolveWorksheetRoute
  '/app/learn/': typeof AppLearnIndexRoute
  '/app/solve/': typeof AppSolveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/app/exams': typeof AppExamsRoute
  '/app/library': typeof AppLibraryRoute
  '/app/my-cooks': typeof AppMyCooksRoute
  '/app/plan': typeof AppPlanRoute
  '/app/practice': typeof AppPracticeRoute
  '/app/progress': typeof AppProgressRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/learn/$lessonId': typeof AppLearnLessonIdRoute
  '/app/solve/$id': typeof AppSolveIdRoute
  '/app/solve/worksheet': typeof AppSolveWorksheetRoute
  '/app/learn': typeof AppLearnIndexRoute
  '/app/solve': typeof AppSolveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/exams': typeof AppExamsRoute
  '/app/learn': typeof AppLearnRouteWithChildren
  '/app/library': typeof AppLibraryRoute
  '/app/my-cooks': typeof AppMyCooksRoute
  '/app/plan': typeof AppPlanRoute
  '/app/practice': typeof AppPracticeRoute
  '/app/progress': typeof AppProgressRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/learn/$lessonId': typeof AppLearnLessonIdRoute
  '/app/solve/$id': typeof AppSolveIdRoute
  '/app/solve/worksheet': typeof AppSolveWorksheetRoute
  '/app/learn/': typeof AppLearnIndexRoute
  '/app/solve/': typeof AppSolveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/exams'
    | '/app/learn'
    | '/app/library'
    | '/app/my-cooks'
    | '/app/plan'
    | '/app/practice'
    | '/app/progress'
    | '/app/quiz'
    | '/app/settings'
    | '/app/'
    | '/app/learn/$lessonId'
    | '/app/solve/$id'
    | '/app/solve/worksheet'
    | '/app/learn/'
    | '/app/solve/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/app/exams'
    | '/app/library'
    | '/app/my-cooks'
    | '/app/plan'
    | '/app/practice'
    | '/app/progress'
    | '/app/quiz'
    | '/app/settings'
    | '/app'
    | '/app/learn/$lessonId'
    | '/app/solve/$id'
    | '/app/solve/worksheet'
    | '/app/learn'
    | '/app/solve'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/exams'
    | '/app/learn'
    | '/app/library'
    | '/app/my-cooks'
    | '/app/plan'
    | '/app/practice'
    | '/app/progress'
    | '/app/quiz'
    | '/app/settings'
    | '/app/'
    | '/app/learn/$lessonId'
    | '/app/solve/$id'
    | '/app/solve/worksheet'
    | '/app/learn/'
    | '/app/solve/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exams': {
      id: '/app/exams'
      path: '/exams'
      fullPath: '/app/exams'
      preLoaderRoute: typeof AppExamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learn': {
      id: '/app/learn'
      path: '/learn'
      fullPath: '/app/learn'
      preLoaderRoute: typeof AppLearnRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-cooks': {
      id: '/app/my-cooks'
      path: '/my-cooks'
      fullPath: '/app/my-cooks'
      preLoaderRoute: typeof AppMyCooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plan': {
      id: '/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/practice': {
      id: '/app/practice'
      path: '/practice'
      fullPath: '/app/practice'
      preLoaderRoute: typeof AppPracticeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quiz': {
      id: '/app/quiz'
      path: '/quiz'
      fullPath: '/app/quiz'
      preLoaderRoute: typeof AppQuizRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learn/': {
      id: '/app/learn/'
      path: '/'
      fullPath: '/app/learn/'
      preLoaderRoute: typeof AppLearnIndexRouteImport
      parentRoute: typeof AppLearnRoute
    }
    '/app/learn/$lessonId': {
      id: '/app/learn/$lessonId'
      path: '/$lessonId'
      fullPath: '/app/learn/$lessonId'
      preLoaderRoute: typeof AppLearnLessonIdRouteImport
      parentRoute: typeof AppLearnRoute
    }
    '/app/solve/': {
      id: '/app/solve/'
      path: '/solve'
      fullPath: '/app/solve/'
      preLoaderRoute: typeof AppSolveIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/solve/$id': {
      id: '/app/solve/$id'
      path: '/solve/$id'
      fullPath: '/app/solve/$id'
      preLoaderRoute: typeof AppSolveIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/solve/worksheet': {
      id: '/app/solve/worksheet'
      path: '/solve/worksheet'
      fullPath: '/app/solve/worksheet'
      preLoaderRoute: typeof AppSolveWorksheetRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppLearnRouteChildren {
  AppLearnLessonIdRoute: typeof AppLearnLessonIdRoute
  AppLearnIndexRoute: typeof AppLearnIndexRoute
}

const AppLearnRouteChildren: AppLearnRouteChildren = {
  AppLearnLessonIdRoute: AppLearnLessonIdRoute,
  AppLearnIndexRoute: AppLearnIndexRoute,
}

const AppLearnRouteWithChildren = AppLearnRoute._addFileChildren(
  AppLearnRouteChildren,
)

interface AppRouteChildren {
  AppExamsRoute: typeof AppExamsRoute
  AppLearnRoute: typeof AppLearnRouteWithChildren
  AppLibraryRoute: typeof AppLibraryRoute
  AppMyCooksRoute: typeof AppMyCooksRoute
  AppPlanRoute: typeof AppPlanRoute
  AppPracticeRoute: typeof AppPracticeRoute
  AppProgressRoute: typeof AppProgressRoute
  AppQuizRoute: typeof AppQuizRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSolveIdRoute: typeof AppSolveIdRoute
  AppSolveWorksheetRoute: typeof AppSolveWorksheetRoute
  AppSolveIndexRoute: typeof AppSolveIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExamsRoute: AppExamsRoute,
  AppLearnRoute: AppLearnRouteWithChildren,
  AppLibraryRoute: AppLibraryRoute,
  AppMyCooksRoute: AppMyCooksRoute,
  AppPlanRoute: AppPlanRoute,
  AppPracticeRoute: AppPracticeRoute,
  AppProgressRoute: AppProgressRoute,
  AppQuizRoute: AppQuizRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppSolveIdRoute: AppSolveIdRoute,
  AppSolveWorksheetRoute: AppSolveWorksheetRoute,
  AppSolveIndexRoute: AppSolveIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
